### ISSUE TITLE
ArrayIndexOutOfBoundsException after Segment Cropper

### ISSUE THREAD

**Issue by imagejan** [knime-ip/knip#346]
The Segment Cropper seems to mix up the image offsets. When cropping a segment from a large image, subsequent nodes (e.g. DoG Spot Detection) can throw an `ArrayIndexOutOfBoundsException`.

Have a look at the following workflow illustrating the issue:
[Segment_Cropper_Offset_Bug.zip](https://github.com/knime-ip/knip/files/297478/Segment_Cropper_Offset_Bug.zip)

I also noticed that the value displayed upon mouseover on the cropped segments in the image viewer is always 0, although the cropped image is displayed correctly.

**Comment by tibuch** [comment]
fixed with ecc324c4281833ca71704ebea20f166572421e0a

**Comment by imagejan** [comment]
Thanks for fixing the AIOOException!

> I also noticed that the value displayed upon mouseover on the cropped segments in the image viewer is always 0, although the cropped image is displayed correctly.

The above issue remains however: both cropped image segments and cropped labelings have mouse-over values of 0, although there is clearly some signal/label at the cursor position.

Is this a known problem, or should we file another issue for this?

**Comment by dietzc** [comment]
Known problem. I just got an example workflow from @tibuch! I will take a look tonight! :+1:

**Comment by imagejan** [comment]
Thanks, @dietzc! Actually, I just noticed with the current nightly build that also other nodes seem to have issues after Segment Cropper: the Gaussian Convolution created an all-black image, for example.

**Comment by dietzc** [comment]
Thanks for noticing - I will run a full node test with shifted intervals and fix all upcoming errors!

**Comment by dietzc** [comment]
Hi @imagejan. I fixed the problem with the `zero` values in the `ViewInfo`. However, I couldn't reproduce the problem you mentoined with gauss. Could you provide a very small example workflow? Then I can fix it tomorrow. Thanks!

**Comment by imagejan** [comment]
Hm, I'm actually not sure if the nightly build I installed/updated yesterday includes @tibuch's original fix. I now noticed that I still see errors with the Spot Detection after the Segment Cropper:

```
ERROR Spot Detection       3:5        Error in row img_UNSIGNEDBYTETYPE_net.imglib2.img.array.ArrayImgFactory@6e85dff9_0#Unknown: java.lang.ArrayIndexOutOfBoundsException: 66981919
ERROR Spot Detection       3:5        Execute failed: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: 66981919
```

Here's an updated version of the workflow I tested:
[Segment_Cropper_Offset_Bug.zip](https://github.com/knime-ip/knip/files/304338/Segment_Cropper_Offset_Bug.zip)

When creating a freehand annotation in the bottom right corner of the generated image via the Interactive Annotator, I now get a black (all-zero) image in the Gaussian Deconvolution, and the above error in the Spot Detection. The DoG Spot Detection runs fine however.

(I tested with `KNIME Image Processing	1.4.2.201606070603`)

**Comment by dietzc** [comment]
thanks @imagejan. I was able to reproduce and fix one problem (empty image after gauss). I'm now manually building the nightly-built - it should be ready in about 45min. Can you test again and see if there is any problem open? Thanks for your efforts!

**Comment by imagejan** [comment]
@dietzc thanks a lot!
Works as expected now with `KNIME Image Processing	1.4.2.201606090603`. :+1:

**Comment by dietzc** [comment]
perfect. thanks for the feedback. there were some glitches, but I hope it's fine now. I will cut a release with the next KNIME release.
