### ISSUE TITLE
Structuring Element Node: third dimension should default to "Z"

### ISSUE THREAD

**Issue by imagejan** [knime-ip/knip#372]
Currently, when changing the number of dimensions in Sphere or Box configuration to 3, the newly added dimension is "Unknown". In most use cases, "Z" should be a sensible default.

**Comment by AndreasBurger** [comment]
Fixed this bug. I've fixed the order of the axis-labels to X, Y, Z, T, C, Unknown, Unknown, ...

**Comment by imagejan** [comment]
Still doesn't work in `KNIME Image Processing	1.5.2.201607190650`: the resulting 3D Sphere element has the dimensions `X,Y,Unknown`

**Comment by AndreasBurger** [comment]
As of 2ca9880bc4e927d57e348058f26e053ddb698448 the meta-information is passed along and the axes should be labeled as mentioned before.
