### ISSUE TITLE
Source is lost when merging images

### ISSUE THREAD

**Issue by maierl** [knime-ip/knip#380]
The _Merger_ doesn't keep the Image source (or the calibration #282).
Merging images with _GroupBy_ keeps the calibration, but not the source.

**Comment by hornm** [comment]
Fixed with https://github.com/knime-ip/knip/commit/9b01f81012666b292e23b56bd5efe5289b2613d4

**Comment by maierl** [comment]
thanks for your quick fix!
that doesn't fix the lost source in the GroupBy node, does it?
