### ISSUE TITLE
Feature Calculator throws exception

### ISSUE THREAD

**Issue by imagejan** [knime-ip/knip#393]
When using _Feature Calculator (BETA)_ with any of the Statistic Features (e.g. in the _06_Feature_Calculation_ example workflow), I get the following exception (tested with KNIP `1.5.2.201609050651`):

```
ERROR Feature Calculator (BETA) 10:13      Execute failed: No matching 'net.imagej.ops.Ops$Stats$Min/net.imagej.ops.special.function.UnaryFunctionOp' op

Request:
-	net.imagej.ops.Ops$Stats$Min/net.imagej.ops.special.function.UnaryFunctionOp(
		IntervalView,
		null,
		Object[])

Candidates:
1. 	(RealType out) =
	org.knime.knip.features.sets.optimizedfeatures.OptimizedMin(
		Iterable in)
	Too many arguments: 3 > 1
2. 	(RealType out?) =
	net.imagej.ops.stats.IterableMin(
		RealType out?,
		Iterable in)
	Too many arguments: 3 > 2
```

**Comment by dietzc** [comment]
thanks for reporting @imagejan, must be some change in `Ops` causing this problem. I will take a look asap.

**Comment by dietzc** [comment]
fixed with next nightly build.

**Comment by imagejan** [comment]
@dietzc is there a new nightly build available? I still see `1.5.2.201609160651` as most recent version.

**Comment by dietzc** [comment]
not yet. our server is still down as we move it to another one. I hope that there will be a new nightly build tomorrow evening.
